version: '3.7'

networks:
  portal:
    driver: bridge

services:
  redis:
    restart: on-failure
    image: redis:latest
    init: true
    container_name: portal_redis
    networks:
      - portal
    command: [redis-server, --requirepass LphfNOPZi0kxReGtJTMmVjVrjFbDY7s8]
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s