# Generated by Django 4.1.2 on 2022-10-31 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_remove_post_category_postcategory_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, max_length=200, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
